### ISSUE TITLE
Capybara::Webkit::ConnectionError

### ISSUE THREAD

**Issue by Stoner19** [mattr-/slack-emoji-upload#1]
After I run `bundle` and `SLACK_DOMAIN=foo SLACK_EMAIL=bar@example.com SLACK_PASSWORD="myf4ncyp455w0rd" bundle exec ruby ./slack_emoji_upload.rb` (with all of the proper criteria changed) I get:

`Importing 522 emoji
Logging into Slack for slackteamname
/var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/connection.rb:87:in `parse_port': /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/bin/webkit_server failed to start. (Capybara::Webkit::ConnectionError)
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/connection.rb:93:in `discover_port'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/connection.rb:74:in `start_server'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/connection.rb:31:in `initialize'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/driver.rb:14:in `new'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit/driver.rb:14:in `initialize'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit.rb:15:in `new'
    from /var/lib/gems/2.3.0/gems/capybara-webkit-1.8.0/lib/capybara/webkit.rb:15:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/capybara-2.6.2/lib/capybara/session.rb:84:in `driver'
    from /var/lib/gems/2.3.0/gems/capybara-2.6.2/lib/capybara/session.rb:232:in `visit'
    from ./slack_emoji_upload.rb:30:in `<main>'`

**Comment by mattr-** [comment]
Are you running this on Linux?

**Comment by Stoner19** [comment]
Tried in both Ubuntu server 14.04 and OSX
